### PR TITLE
Update to python 3 print syntax...

### PR DESCRIPTION
**Pull request by DJStompZone**
This... DOES use python 3 right?

### CODE REVIEW

**Comment by dktapps** [comment]
No, it doesn't use Python 3.

**Comment by dktapps** [comment]
Sorry for being so abrupt ...

The code isn't written for Python 3, and I'm not inclined to spend the time to update it. The benefit for a project like this is close to zero anyway. In fact, it could just as easily have been written in PHP or some other language. The only reason it's in Python at all is because this is based on a very old tool I've been using since 2017.

TL;DR: If it isn't broken, don't mess with it.

**Comment by dktapps** [comment]
I've fixed the incorrect documentation on the README, thanks for drawing my attention to it.

**Comment by DJStompZone** [comment]
> No, it doesn't use Python 3.

It does now. [Check my fork](https://github.com/DJStompZone/BedrockProtocolDumper), I got it running on python 3.10

**Pull request closed without merging**
